[main]
header_limit = 16384
body_limit = 2097152
keepalive_timeout = 30
keepalive_max_requests = 100
open_file_cache_max = 128
open_file_cache_inactive = 30
proxy_timeout = 10

[server:demo]
listen = 0.0.0.0:8080
server_name = astrxgore.ru localhost 127.0.0.1
root = public
autoindex = on
access_log = logs/access.log

[location:demo:/]
root = public
autoindex = on

[location:demo:/api/]
proxy_pass = http://127.0.0.1:9000

[server:alt]
listen = 0.0.0.0:8080
server_name = alt.astrxgore.ru alt.local second.local
root = public_alt
autoindex = on
access_log = logs/access.log

[location:alt:/]
root = public_alt
autoindex = on
